[package]
name = "mkspy"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"

[dependencies.iced]
version = "0.10.0"
features = ["smol"]

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
]
